### ISSUE TITLE
/APP/Timeline/favoritePlurks api not working

### ISSUE THREAD

**Issue by chenyunhsin** [clsung/plurk-oauth#14]
Traceback (most recent call last):
  File "/Users/yunhsinchen/plurkBot/plurk-oauth/bot.py", line 81, in <module>
    plurk.callAPI('/APP/Timeline/favoritePlurks', {'ids': [pid]})
  File "/Users/yunhsinchen/plurkBot/plurk-oauth/plurk_oauth/api.py", line 48, in callAPI
    self._error['code'], self._json, self._error['reason'] = self._oauth.request(
  File "/Users/yunhsinchen/plurkBot/plurk-oauth/plurk_oauth/oauth.py", line 60, in request
    req = self._make_request(self.base_url + url, data)
  File "/Users/yunhsinchen/plurkBot/plurk-oauth/plurk_oauth/oauth.py", line 109, in _make_request
    request = Request.from_consumer_and_token(consumer=self.consumer,
  File "/usr/local/lib/python3.9/site-packages/oauth2/__init__.py", line 577, in from_consumer_and_token
    return cls(http_method, http_url, parameters, body=body, 
  File "/usr/local/lib/python3.9/site-packages/oauth2/__init__.py", line 355, in __init__
    v = to_unicode_optional_iterator(v)
  File "/usr/local/lib/python3.9/site-packages/oauth2/__init__.py", line 142, in to_unicode_optional_iterator
    return [ to_unicode(e) for e in l ]
  File "/usr/local/lib/python3.9/site-packages/oauth2/__init__.py", line 142, in <listcomp>
    return [ to_unicode(e) for e in l ]
  File "/usr/local/lib/python3.9/site-packages/oauth2/__init__.py", line 99, in to_unicode
    raise TypeError('You are required to pass either unicode or '
TypeError: You are required to pass either unicode or bytes here, not: <class 'int'> (1475070355)

I saw this api's required parameters is:
ids: The plurk ids, formated as JSON, e.g. [342,23242,2323]
is ids a unicode or int list?

**Comment by chenyunhsin** [comment]
I find the way to use this api, my fault :p
 plurk.callAPI('/APP/Timeline/favoritePlurks', {'ids': "["+str(pid)+"]"})
